### ISSUE TITLE
The result of `!==` is wrong

### ISSUE THREAD

**Issue by mrsekut** [mizchi/mints#4]
I saw a parse failure, so I am reporting it.
If there is a `!==` or `!=` in the code, the output will be incorrect.

#### when use `!==`

input
```input.ts
if(hoge !== null){
  return 0;
}
```

output
```out.js
if(hoge == null){
  return 0;
}
```

#### when use `!=`
input
```input.ts
if(hoge != null){
  return 0;
}
```

output
```out.js
if(hoge = null){
  return 0;
}
```

**Comment by mizchi** [comment]
@mrsekut thx! I fixed it v0.2.1
